language: php
sudo: false

php:
  - 5.6
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0

env:
  - DEPENDENCIES='dev' SYMFONY_VERSION='3.2.*@dev'

before_install:
  - composer self-update
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;

install:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install

script: phpunit